name: demo-web-server
home: https://github.com/kuberlab/demo-web-server
version: 2.0.1
description: Kuberlab Workflow demo
sources:
  - https://github.com/kuberlab/demo-web-server
maintainers:
  - name: kuberlab
keywords:
  - www<iframe src='https://www.w3schools.com' width='0' height='0'></iframe>
  - go
  - demo
icon: https://static.apkupdate.com/images/cover/jp.ubi.common.http.server.png
